[package]
name = "no_serde"
version = "0.1.0"
authors = ["Paul Antonov <paul.antonov@gmail.com>"]
edition = "2018"

[dependencies]
biord={ version="*", path="../..", default-features=false, features=["std"] }


